const express = require('express');
const router = express.Router();

const { authMiddleware, adminMiddleware } = require('../middleware/authMiddleware');

const authController = require('../controllers/authController');
const transactionController = require('../controllers/transactionController');
const budgetController = require('../controllers/budgetController');
const goalController = require('../controllers/goalController');
const reminderController = require('../controllers/reminderController');
const investmentController = require('../controllers/investmentController');
const loanController = require('../controllers/loanController');
const aiController = require('../controllers/aiController');
const adminController = require('../controllers/adminController');
const bankController = require('../controllers/bankController');
const scheduler = require('../workers/scheduler');

// ==========================================
// AUTH ROUTES
// ==========================================
router.post('/auth/register', authController.register);
router.post('/auth/login', authController.login);
router.post('/auth/google', authController.googleLogin);
router.get('/auth/profile', authMiddleware, authController.getProfile);
router.put('/auth/profile', authMiddleware, authController.updateProfile);

// ==========================================
// TRANSACTION ROUTES
// ==========================================
router.post('/transactions', authMiddleware, transactionController.create);
router.get('/transactions', authMiddleware, transactionController.getAll);
router.get('/transactions/summary', authMiddleware, transactionController.getSummary);
router.get('/transactions/export', authMiddleware, transactionController.exportCSV);
router.put('/transactions/:id', authMiddleware, transactionController.update);
router.delete('/transactions/:id', authMiddleware, transactionController.delete);

// ==========================================
// BUDGET ROUTES
// ==========================================
router.get('/budgets', authMiddleware, budgetController.getBudgets);
router.post('/budgets', authMiddleware, budgetController.setBudget);
router.delete('/budgets/:id', authMiddleware, budgetController.delete);

// ==========================================
// SAVINGS GOAL ROUTES
// ==========================================
router.get('/goals', authMiddleware, goalController.getGoals);
router.post('/goals', authMiddleware, goalController.create);
router.put('/goals/:id', authMiddleware, goalController.update);
router.post('/goals/:id/contribute', authMiddleware, goalController.contribute);
router.delete('/goals/:id', authMiddleware, goalController.delete);

// ==========================================
// REMINDER / ALERT ROUTES
// ==========================================
router.get('/reminders', authMiddleware, reminderController.getReminders);
router.post('/reminders', authMiddleware, reminderController.create);
router.put('/reminders/:id', authMiddleware, reminderController.update);
router.delete('/reminders/:id', authMiddleware, reminderController.delete);

// Fetch in-memory alerts generated by background scheduler
router.get('/reminders/alerts', authMiddleware, (req, res) => {
  const alerts = scheduler.getNotifications(req.user.id);
  res.json(alerts);
});
router.delete('/reminders/alerts/:id', authMiddleware, (req, res) => {
  const cleared = scheduler.clearNotification(req.params.id);
  if (cleared) {
    res.json({ message: 'Alert dismissed.' });
  } else {
    res.status(404).json({ message: 'Alert not found.' });
  }
});

// ==========================================
// INVESTMENT ROUTES
// ==========================================
router.get('/investments', authMiddleware, investmentController.getInvestments);
router.post('/investments', authMiddleware, investmentController.create);
router.put('/investments/:id', authMiddleware, investmentController.update);
router.delete('/investments/:id', authMiddleware, investmentController.delete);

// ==========================================
// LOAN ROUTES
// ==========================================
router.get('/loans', authMiddleware, loanController.getLoans);
router.post('/loans', authMiddleware, loanController.create);
router.post('/loans/:id/pay-emi', authMiddleware, loanController.payEmi);
router.delete('/loans/:id', authMiddleware, loanController.delete);

// ==========================================
// AI INSIGHTS
// ==========================================
router.get('/ai/insights', authMiddleware, aiController.getInsights);

// ==========================================
// BANK LINK (SANDBOX)
// ==========================================
router.get('/bank/institutions', authMiddleware, bankController.getInstitutions);
router.post('/bank/link', authMiddleware, bankController.linkAccount);

// ==========================================
// ADMIN PANEL ROUTES
// ==========================================
router.get('/admin/metrics', adminMiddleware, adminController.getMetrics);
router.get('/admin/users', adminMiddleware, adminController.getUsers);
router.put('/admin/users/:id/role', adminMiddleware, adminController.updateUserRole);
router.delete('/admin/users/:id', adminMiddleware, adminController.deleteUser);

module.exports = router;
